#+TITLE: Little Languages
#+DATE: <2025-04-13 dom>

Many of the languages mentioned were born around 1970 at Bell labs.

regex https://xkcd.com/208/

https://blog.cloudflare.com/details-of-the-cloudflare-outage-on-july-2-2019/


* Why?

- Why learn new programming languages as an already profesional software developer on X language?
  - We often hear the phrase once you learn C every other language is a variation of the same.
    - I only partially agree with it.
    - What C brings is a [model of computation](https://en.wikipedia.org/wiki/Model_of_computation) that one should follow to solve problems.
    - That said, it's far from being the only one.
  - Why learn a new way to solve the same problem?
    - It help us apply concepts and axioms we blindly believed to be true into new contexts. Allowing use to gain new enlightment on their *raison d'etre*.
      - For example, we might have learned to keep function arity low. But we might truly understand it after trying to juggle function parameters in a *concatenative* programming language or by trying to *compose* functions in a *functional* programming language.

* 71 sh
* 71 roff

ossana 43, ken thompson 28

text formatting

* 71 dc

- Bell Labs
- Robert H. Morris (39)
- Lorinda Cherry (27)
- arbitrary precision arithmetic calculator
- stack based

#+CAPTION: hexa to binary
#+begin_src sh
  $ dc
  2o 16i 80 p
  10000000
#+end_src

* 74 sed

Bell Labs
"Stream EDitor"
Lee E. McMahon (43)

ADDRESS? COMMAND

- text line editing
- line addressing

* 76 Make

Bell Labs
Stuart Feldman

incremental rebuilds

TARGET: DEPENDENCIES
    COMMAND

* 75 bc

- arithmethic
- frontend for dc

* 77 m4

- Brian Kernighan, Dennis Ritchie
- Macro preprocessor
- Can be used to:
  - extend other languages.
  - template html

* 77 AWK

aho (36), pjw (35), bwk (35)

PATTERN? { ACTION }

- validation
- exploratory data analysis
- networking?

* 82 PostScript

- Adobe
- John Warnock(42), Chuck Geschke(43), Doug Brotz, Ed Taft, Bill Paxton

* 84 pic

bwk (42)

* 87 imagemagick

- https://codegolf.meta.stackexchange.com/questions/8828/is-imagemagick-a-programming-language
  - fx()
    - hypot(x,y) == glsl length() on vec2
    - distance(x,y) in glsl is length(x-y)
  - stack based operations
  - () is like shell command substitution

* 12 jq
* Other

- lex 75, yacc 75, latex 84, regex, cpp, find, vim(script)
- ffmpeg filters
- imagemagick draw api
- ixilang https://en.wikipedia.org/wiki/Ixi_lang
- bitcoin script

* References

- https://en.wikipedia.org/wiki/Turing_tarpit
  - PL that allows for flexibility in function but is difficult to learn and use because it offers little or no support for common tasks.

- 86 [[https://www.cs.toronto.edu/~chechik/courses18/csc2125/paper13.pdf][Programming Pearls]] by Jon Bentley
- 99 The Practice of Programming by Kernighan & Pike
  Little languages are specialized notations for narrow domains. They not only provide a good interface but also help organize the program that implements them. The printf control sequences are a good example...
- 11 COSC345 pdf https://www.cs.otago.ac.nz/cosc345/Lectures2011/L2-Little-Languages-and-Assignment.pdf
- 19 https://comp590-19s.github.io/
  https://comp590-19s.github.io/docs/lectures
  https://comp590-19s.github.io/docs/lec/00-welcome.pdf
  - by Kris Jordan
  - trial course
- 19 COS333 pdf https://www.cs.princeton.edu/courses/archive/spring19/cos333/18litlang.pdf
- 19 https://www.youtube.com/watch?v=xnCgoEyz31M
  - https://lobste.rs/s/mdmcdi/little_languages_by_jon_bentley_1986
  - https://news.ycombinator.com/item?id=40989069
- https://wiki.c2.com/?LittleLanguage
  What Bell Labs did was to make separate languages for the tasks they found, and optimized them for those tasks.
- ?? ANON
  "I view it in the same light as Microsoft Excel: good at what it does, but too powerful for its own good.
   If your not careful, it will grow until you wish you had been using a proper programming language from the begging."
